oxidecomputer/cobalt

hdl/BUILD
hdl/PLL.bsv
hdl/boards/ecp5_evn/BUILD
hdl/boards/ecp5_evn/Examples.bsv
hdl/interfaces/BUILD
hdl/interfaces/ECP5.bsv
hdl/interfaces/ECP5PLL.v

This diff adds a rudimentary wrapper around the EXHPLLL PLL primitive for the ECP5 family. You'll currently have to fill out the parameters by hand, which can be obtained by running the `ecppll` util provided by nextpnr-ecp5. Future work could port the calculations performed by that util into some Bluespec functions allowing the compiler to compute parameters at compile time.

Add rudimentary ECP5 PLL wrapper/abstraction

---

hdl/interfaces/BUILD
hdl/interfaces/ICE40.bsv

This PR adds rudimentary wrappers for the iCE40 SB_IO primitive. The differential variants have been tested on a board.

Add wrappers for iCE40 IO primitives

---

hdl/BUILD
hdl/examples/BUILD
hdl/interfaces/BUILD
hdl/test/BUILD
tools/site_cobble/bluespec.py

This diff adds a `bluesim_tests` macro to the `bluespec` Cobble plugin, allowing Bluesim test suites to be declared with much less overhead. For example:
```python
bluesim_tests('Encoding8b10bTests',
env = 'bluesim_default',
suite = 'Encoding8b10bTest.bsv',
modules = [
'mkEncoderTest',
'mkConnectTest',
'mkDisconnectTest',
],
deps = [
'//hdl:Encoding8b10b',
'//hdl:TestUtils',
])
```
Resulting in the following build targets to be made available:
```
latest/hdl/test/Encoding8b10bTests_mkConnectTest
latest/hdl/test/Encoding8b10bTests_mkDisconnectTest
latest/hdl/test/Encoding8b10bTests_mkEncoderTest
```
See other BUILD files in this diff for additional examples.

Add bluesim_tests macro, refactor tests

---

hdl/BUILD
hdl/Strobe.bsv
hdl/interfaces/UART.bsv

- Provide a strobe template, to make it easier to implement alternative strobes
- Add LimitStrobe, used for precise, jitter free strobes
- Add mkFreeRunningStrobe util module
- Allow downcasting a Strobe to PulseWire if desired
- Add missing tests for each strobe type
Test results:
```
./cobble bluesim_test //hdl:StrobeTests
4 query result(s)
ninja: no work to do.
//hdl:StrobeTests
PASS   (0:00:00.260)   .. mkFractionalStrobeTest
PASS   (0:00:00.279)   .. mkLimitStrobeStrobeTest
PASS   (0:00:00.291)   .. mkPowerTwoStrobeAsCountDownTest
PASS   (0:00:00.299)   .. mkPowerTwoStrobeTest
Build Time:             0:00:00.030
Test Time:              0:00:01.136
Total/Passed/Failed:    4/4/0
```

Strobe improvements

---

hdl/interfaces/ICE40.bsv

- Add a differential input/output typedef
- Remove obsolete mkInitialReset (moved to its own module in hdl/)
- Fix enum typo
- Small readability improvements when instantiating vMk_SB_IO

Add diff IO typedef, small clean ups

---

tools/site_cobble/nextpnr.py

Name Nextpnr bitstream outputs in the Cobble build graph, allowing build commands like:
```
~/quartz/build$ ./cobble build //hdl/boards/ignition.*#bitstream
4 query result(s)
...
```

Name Nextpnr bitstream outputs

---

tools/site_cobble/yosys.py

`cxxrtl` targets used as dependencies come with some implicit include paths for compilation to succeed. One of these include paths was constructed manually, missing the fact that a project may be a subproject instead of the root project. Using `Project.outpath(..)` correctly takes this into account, allowing these dependencies to be used across project boundaries.

Fix include path for cxxrtl deps in subprojects

---

hdl/BUILD
hdl/Countdown.bsv

Add a Countdown module, intended for things like generating timeout events, delays, etc.

Add Countdown module

---

BUILD.conf
vnd/bluespec/BUILD

Originally it was "Disabled until we figure out how to suppress the Yosys warning." and, well, we can do that.

Enables use of bluespec's TriState module

---

tools/site_cobble/bsv_fpga_version.py
tools/site_cobble/gen_git_version_bsv.py
tools/site_cobble/rdl_pkg/templates/regpkg_bsv.jinja2

Git fix:
I know this is a hack but this felt like the least-invasive way of solving this issue right now, and it limited the scope to changes in cobalt. Essentially we unconditionally run some code (on plugin import no less!) that gets the current git information and creates/updates a .json file in the build directory when necessary.  This file is *magically* added as an input dependency for the generated version bsv so ninja can build a dep map and "work".  The generation script now opens this generated json and deserializes it, using the values to generate the bsv. This better fits the ninja pattern of files and dependencies while basically ignoring the cobble fanciness.  We can't use cobble variables here because at import we have no env so none of the variables are accessible.  Fixes …

Improve reset generation using defaultValue and fix stale git SHAs

---

RDL_EXAMPLES.md
tools/site_cobble/rdl.py
tools/site_cobble/rdl_pkg/demo.rdl
tools/site_cobble/rdl_pkg/demo_top.rdl
tools/site_cobble/rdl_pkg/exporter.py
tools/site_cobble/rdl_pkg/listeners.py
tools/site_cobble/rdl_pkg/models.py
tools/site_cobble/rdl_pkg/rdl_cli.py
tools/site_cobble/rdl_pkg/templates/regmap_html.jinja2
tools/site_cobble/rdl_pkg/templates/regpkg_bsv.jinja2
tools/site_cobble/rdl_pkg/templates/toplvl_bsv.jinja2

Fixes #30.  RegFiles are now supported and work correctly.
Fixes #29. This now works in the following way:
- An AddrMap with only register and RegFile definitions generates like normal.
- An AddrMap containing a mix of AddrMaps and registers/Regfiles is not really tested but will likely generate like the first case, but totally flattened.
- An AddrMap containing other AddrMaps generates special bsv top file that just contains the offsets and an html map of the complete chip with flattened names.  Json output here is TBD.
A side-effect of this update is that types are now properly shared, meaning we only create a single struct and TypeClasses for this shared type, while still providing the enumerated offsets for each instance. 
- This can have minor code impact since the shared type name …

Deal with RegFiles and nested address maps more correctly

---

hdl/BUILD
hdl/SchmittReg.bsv

This diff fixes the SchmittReg tests, which have been broken for a while. Once landed all current cobalt tests should run/pass as follows:
```
./cobble bluesim_test //.*Tests
```
Or from another repo which may depend on cobalt as a submodule:
```
./cobble bluesim_test cobalt//.*Tests
```

Fix SchmittReg tests, add slow filter test case

---

hdl/BUILD
hdl/WriteOnceReg.bsv

WriteOnceReg is a wrapper around Reg which allows it to be written only once. This can for example be used to implement soft fuses.

Add WriteOnceReg

---

BUILD.conf

The `bluesim_debug` environment is intended to enable additional signals in waveform dumps to help understanding a design (at the expense of somewhat longer sim times due to additional logging). As such it should inherit from the `bluesim_default` environment.

Make bluesim_debug env inherit from bluesim_default

---

RDL_EXAMPLES.md
tools/site_cobble/rdl_pkg/json_dump.py
tools/site_cobble/rdl_pkg/listeners.py
tools/site_cobble/rdl_pkg/models.py
tools/site_cobble/rdl_pkg/templates/regmap_html.jinja2
tools/site_cobble/rdl_pkg/templates/regpkg_bsv.jinja2

This added RDL-specified enums to generate enums in the BSV package.  This is the first step in a series of steps to getting this end-end supported, but this was complete and useful now on the bsv side so I'm breaking this out separately.
Future work includes work on the rust generation side to generate Rust Enums also.  This was more invasive to our current Rust generation workflow and so will be done separately.
Right now, this fixes the html generation and the bsv package generation, leaving the json/rust stuff for future work.
Additionally, BSV has no way of disambiguating multiple enum members with the same name in the same package so we throw errors if you have conflicting enum names since we're generating one big package here.

Adding bsv enum generation from rdl enums

---

hdl/interfaces/video/BUILD
hdl/interfaces/video/TMDS.bsv
hdl/interfaces/video/TestPatternGenerator.bsv

It looks like some video packages were missed in https://github.com/oxidecomputer/cobalt/pull/12 and https://github.com/oxidecomputer/cobalt/pull/41. This was discovered while working on build system improvements.

Fix deprecated assert_* calls in video tests, use bluesim_test(..)

---

hdl/Countdown.bsv
hdl/InitialReset.bsv
hdl/SchmittReg.bsv
hdl/Strobe.bsv
hdl/boards/ecp5_evn/Examples.bsv
hdl/boards/icestick/Examples.bsv
hdl/boards/ulx3s/Examples.bsv
hdl/examples/TestPatternVideoSource.bsv
hdl/examples/UARTLoopback.bsv
hdl/interfaces/SPI.bsv
hdl/interfaces/UART.bsv
hdl/interfaces/video/TMDS.bsv
hdl/interfaces/video/TestPatternGenerator.bsv
hdl/interfaces/video/Timing.bsv
hdl/test/Encoding8b10bTests.bsv
tools/site_cobble/bluespec.py

Cobble takes a bit of a shotgun approach to generating Verilog/Bluesim modules from Bluespec package files; all modules in a file from which outputs should be generated are annotated with the `synthesize` attribute and BSC is called using the `-verilog` or `-sim` output mode. BSC then iterates through the package and sequentially generates output for each annotated module it finds. On the Cobble side the target declares a list of module outputs it expects to be generated. See for example https://github.com/oxidecomputer/cobalt/blob/d8020a844da9ddd4168b77c00e2577d995f1a425/hdl/BUILD#L112
This approach has served us well enough, but it has some drawbacks. One needs to remember to both list the module in the `BUILD` file as well as annotate it in the Bluespec package. Failure to do so …

Generate build rule per delcared Verilog/Bluesim module

---

Dockerfile

I needed to rebuild my dev container after moving to new VM infra. In the process I figured we pick up more recent BSC and Yosys tools to keep up with what's running in CI. Of course this wouldn't compile anymore on ARM (GHC uses an LLVM backend on ARM64, which seems to exhaust its heap when compiling BSC). The latest Ubuntu LTS release comes with a more recent GHC which got me to a working environment.
Our larger designs (Gimlet sequencer, QSFP board controller and Sidecar mainboard controller) and the Ignition test suite all built without problems. Before landing this it would be good if someone with an x86-64 environment tries, but so far everything seems fine.

Update Docker container

---

tools/site_cobble/rdl_pkg/models.py

BSV will let you disambiguate with <typename>'(<enum_name>) where needed

Remove enforcement of no duplicate ENUM fields.  

---

tools/site_cobble/bluespec.py

As per the comment a few lines above this diff, bluesim does not signal an assertion failing using exit codes. Instead the `bluesim_test` runner observes test output and fails a test if it finds assertion failures. Unfortunately that filter was a bit specific allowing continuous assertion failures to go unnoticed.

Fix continuous assertion failing not resulting in test failure
